name: Docker

on:
  push:
    branches: ["master"]
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    strategy:
      matrix:
        target: ["latest", "exporter"]
    uses: "mostpinkest/workflows/.github/workflows/docker.yml@main"
    permissions:
      contents: read
      packages: write
    with:
      dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
      tag: ${{ matrix.target }}
      tag-buildarg: IMAGE_TARGET
      build-cache-map: |
        {
          "go-build-cache": "/root/.cache/go-build",
          "go-package-cache": "/go/pkg"
        }
    secrets:
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

  dockerhub-description:
    uses: "mostpinkest/workflows/.github/workflows/dockerhub-description.yml@main"
    needs:
      - publish
    permissions:
      contents: read
    with:
      dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
    secrets:
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
